import { writable } from 'svelte/store'

export const lockerSection = writable(0)
export const dnsLink = writable(0)
export const ipfsNode = writable(0)
export const hypnsNode = writable(0)
export const wallet = writable(0)
export const username = writable(0)
export const password = writable(0)
export const error = writable(0)
export const deviceType = writable(0)
export const deviceName = writable(0)
export const name = writable(0)
export const did = writable(0)
export const identity = writable(0)
export const opts = writable(0)
